name: FreeBSD clang-scan build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: clang scan build in FreeBSD VM
      id: clang-scan-build
      uses: cross-platform-actions/action@v0.21.0
      with:
        memory: 2048
        shell: sh
        operating_system: freebsd
        version: '13.2'
        run: |
          sudo pkg install -y curl gmake cmake devel/llvm llvm
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          scan-build cmake -B build -DCMAKE_INSTALL_PREFIX=.
          cd build
          scan-build --exclude src/simdjson --status-bugs gmake
